import * as cdk from 'aws-cdk-lib';
import * as s3 from 'aws-cdk-lib/aws-s3';
import * as cloudfront from 'aws-cdk-lib/aws-cloudfront';
import * as origins from 'aws-cdk-lib/aws-cloudfront-origins';
import * as route53 from 'aws-cdk-lib/aws-route53';
import * as route53Targets from 'aws-cdk-lib/aws-route53-targets';
import * as acm from 'aws-cdk-lib/aws-certificatemanager';
import * as s3deploy from 'aws-cdk-lib/aws-s3-deployment';
import {Construct} from 'constructs';
import {buildStaticViewerRequestCode} from './static-viewer-request';
import {recordNameWithinZone} from './record-name';

const DEFAULT_IMMUTABLE_PATTERNS = ['*.js', '*.css', '*.woff2'];
const DEFAULT_LONG_LIVED_PATTERNS = [
    '*.png', '*.jpg', '*.jpeg', '*.webp', '*.avif', '*.svg', '*.gif', '*.ico',
];
const DEFAULT_LONG_LIVED_CACHE_CONTROL = 'public, max-age=2592000';
const DEFAULT_DOCUMENT_CACHE_CONTROL = 'public, max-age=0, must-revalidate';
const IMMUTABLE_CACHE_CONTROL = 'public, max-age=31536000, immutable';
const DEFAULT_PERMISSIONS_POLICY = 'camera=(), microphone=(), geolocation=()';
const DEFAULT_NOT_FOUND_PAGE_PATH = '/404/index.html';

export interface AngularStaticDistributionProps {
    /**
     * Build output directory of a fully prerendered Angular app, i.e. one
     * built with `outputMode: 'static'`. Every route must have a matching
     * index.html; nothing is rendered at request time.
     */
    browserDistPath: string;

    /**
     * All three must be provided together to enable a custom domain + HTTPS.
     * Omit all three to serve from the default CloudFront URL only.
     */
    domainName?: string;
    certificate?: acm.ICertificate;
    hostedZone?: route53.IHostedZone;

    /**
     * When true (default), www.<domainName> is added as a CloudFront alias
     * with Route 53 records, and the viewer-request function 301s it to the
     * apex. Set to false to omit www entirely.
     */
    redirectWwwToApex?: boolean;

    /**
     * Additional aliases on the same certificate. These are treated as
     * canonical, so they serve content rather than redirecting to the apex.
     * They must also be present in the certificate's subjectAlternativeNames;
     * the construct does not modify the certificate.
     */
    additionalDomainNames?: string[];

    /**
     * Legacy path -> new path 301s, served at the edge. Typically generated by
     * the web app's build and read back with `readRedirectManifest`.
     * Matched exactly, so a renamed URL space needs one entry per page.
     */
    redirects?: Record<string, string>;

    /** Fully-assembled CSP string. Build it in the consuming stack. */
    contentSecurityPolicy: string;

    /**
     * Value for the Permissions-Policy response header.
     * Pass an empty string to omit the header entirely.
     */
    permissionsPolicy?: string;

    /** X-Frame-Options header value. Defaults to DENY. */
    frameOption?: cloudfront.HeadersFrameOption;

    /**
     * CloudFront response headers policy name. Must be unique within the AWS
     * account (CloudFront policies are account-global, not per-stack).
     * Defaults to `${stack.stackName}-${id}-SecurityHeaders`.
     */
    securityHeadersPolicyName?: string;

    /**
     * CloudFront function name. Also account-global. Defaults to a name
     * generated from the construct path, which is already unique; set it only
     * when you want the console to show something readable.
     */
    viewerRequestFunctionName?: string;

    /** Extra CloudFront behaviors, e.g. an API path pointed at another origin. */
    additionalBehaviors?: Record<string, cloudfront.BehaviorOptions>;

    /**
     * Key served, with a real 404 status, for any path not in the bucket.
     * Defaults to '/404/index.html', so the app needs a concrete '404' route
     * that prerenders there. A wildcard route alone does not produce the file.
     */
    notFoundPagePath?: string;

    /** Files fingerprinted by the build, served immutable. */
    immutablePatterns?: string[];

    /**
     * Unfingerprinted but slow-changing files. Defaults to image extensions,
     * matched at any depth. Anything not covered here or by
     * `immutablePatterns` falls into the revalidated document tier, which is
     * where data files belong: a JSON payload the app fetches should not be
     * pinned in browser caches for a month.
     */
    longLivedPatterns?: string[];
    longLivedCacheControl?: string;

    /**
     * Cache-Control for everything else, which is mostly HTML. Revalidated on
     * every request so a deploy is visible as soon as the invalidation lands.
     */
    documentCacheControl?: string;

    /**
     * Patterns present in the build output that should not be uploaded, e.g. a
     * redirect manifest that is consumed at synth time rather than served.
     */
    excludeFromUpload?: string[];

    /**
     * Explicit bucket name. Leave unset to let CloudFormation name it: setting
     * it on an existing stack replaces the bucket.
     */
    bucketName?: string;

    /** Defaults to DESTROY with autoDeleteObjects, since the bucket holds only build output. */
    bucketRemovalPolicy?: cdk.RemovalPolicy;

    /** Defaults to PRICE_CLASS_100 (North America and Europe). */
    priceClass?: cloudfront.PriceClass;
}

/**
 * A prerendered Angular site on S3 behind CloudFront, with no origin compute.
 *
 * The sibling of {@link AngularSsrDistribution}. Reach for this one whenever
 * every route can be rendered at build time, which is most content sites: it
 * removes the Lambda, the Web Adapter layer, the function URL and the cold
 * starts, and serves everything from the edge cache over an S3 origin.
 *
 * The three jobs the SSR server was doing for a prerendered app - directory
 * index resolution, legacy redirects, and a real 404 status - move to a
 * viewer-request CloudFront Function and a pair of custom error responses.
 *
 * Use {@link AngularSsrDistribution} instead when content genuinely varies per
 * request: live data, per-user rendering, or anything that must be fresh at the
 * moment of the request rather than the moment of the build.
 */
export class AngularStaticDistribution extends Construct {
    public readonly distribution: cloudfront.Distribution;
    public readonly distributionIdOutput: cdk.CfnOutput;
    public readonly assetsBucket: s3.Bucket;
    public readonly responseHeadersPolicy: cloudfront.ResponseHeadersPolicy;
    public readonly viewerRequestFunction: cloudfront.Function;

    public get distributionId(): string {
        return this.distribution.distributionId;
    }

    constructor(scope: Construct, id: string, props: AngularStaticDistributionProps) {
        super(scope, id);

        const {
            browserDistPath,
            domainName,
            certificate,
            hostedZone,
            redirectWwwToApex = true,
            additionalDomainNames = [],
            redirects = {},
            contentSecurityPolicy,
            permissionsPolicy = DEFAULT_PERMISSIONS_POLICY,
            frameOption = cloudfront.HeadersFrameOption.DENY,
            securityHeadersPolicyName,
            viewerRequestFunctionName,
            additionalBehaviors = {},
            notFoundPagePath = DEFAULT_NOT_FOUND_PAGE_PATH,
            immutablePatterns = DEFAULT_IMMUTABLE_PATTERNS,
            longLivedPatterns = DEFAULT_LONG_LIVED_PATTERNS,
            longLivedCacheControl = DEFAULT_LONG_LIVED_CACHE_CONTROL,
            documentCacheControl = DEFAULT_DOCUMENT_CACHE_CONTROL,
            excludeFromUpload = [],
            bucketName,
            bucketRemovalPolicy = cdk.RemovalPolicy.DESTROY,
            priceClass = cloudfront.PriceClass.PRICE_CLASS_100,
        } = props;

        const stack = cdk.Stack.of(this);

        const domainPropsProvided = [domainName, certificate, hostedZone].filter(Boolean).length;
        if (domainPropsProvided > 0 && domainPropsProvided < 3) {
            throw new Error('domainName, certificate, and hostedZone must all be provided together, or all omitted');
        }

        const aliasesEnabled = !!(domainName && certificate && hostedZone);
        const wwwEnabled = aliasesEnabled && redirectWwwToApex;
        const resolvedHeadersPolicyName = securityHeadersPolicyName ?? `${stack.stackName}-${id}-SecurityHeaders`;

        this.assetsBucket = new s3.Bucket(this, 'AssetsBucket', {
            bucketName,
            blockPublicAccess: s3.BlockPublicAccess.BLOCK_ALL,
            encryption: s3.BucketEncryption.S3_MANAGED,
            enforceSSL: true,
            removalPolicy: bucketRemovalPolicy,
            autoDeleteObjects: bucketRemovalPolicy === cdk.RemovalPolicy.DESTROY,
        });

        // www is deliberately not canonical: it stays an alias so the
        // certificate covers it and visitors who type it land somewhere, but it
        // redirects to the apex like every other non-canonical host.
        this.viewerRequestFunction = new cloudfront.Function(this, 'ViewerRequestFunction', {
            functionName: viewerRequestFunctionName,
            runtime: cloudfront.FunctionRuntime.JS_2_0,
            comment: aliasesEnabled
                ? `Resolve directory indexes; redirect legacy URLs and non-canonical hosts to ${domainName}`
                : 'Resolve directory indexes and redirect legacy URLs',
            code: cloudfront.FunctionCode.fromInline(
                buildStaticViewerRequestCode({
                    redirects,
                    apexDomain: aliasesEnabled ? domainName : undefined,
                    canonicalHosts: aliasesEnabled ? [domainName!, ...additionalDomainNames] : undefined,
                }),
            ),
        });

        this.responseHeadersPolicy = new cloudfront.ResponseHeadersPolicy(this, 'SecurityHeadersPolicy', {
            responseHeadersPolicyName: resolvedHeadersPolicyName,
            securityHeadersBehavior: {
                strictTransportSecurity: {
                    accessControlMaxAge: cdk.Duration.days(365),
                    includeSubdomains: true,
                    preload: true,
                    override: true,
                },
                contentTypeOptions: {override: true},
                frameOptions: {frameOption, override: true},
                referrerPolicy: {
                    referrerPolicy: cloudfront.HeadersReferrerPolicy.STRICT_ORIGIN_WHEN_CROSS_ORIGIN,
                    override: true,
                },
                contentSecurityPolicy: {contentSecurityPolicy, override: true},
            },
            customHeadersBehavior: permissionsPolicy
                ? {
                    customHeaders: [
                        {header: 'Permissions-Policy', value: permissionsPolicy, override: true},
                    ],
                }
                : undefined,
        });

        const functionAssociations: cloudfront.FunctionAssociation[] = [{
            function: this.viewerRequestFunction,
            eventType: cloudfront.FunctionEventType.VIEWER_REQUEST,
        }];

        const resolvedAdditionalBehaviors = Object.fromEntries(
            Object.entries(additionalBehaviors).map(([pattern, behavior]) => [
                pattern,
                {responseHeadersPolicy: this.responseHeadersPolicy, functionAssociations, ...behavior},
            ]),
        );

        const aliasDomains = aliasesEnabled
            ? [domainName!, ...(wwwEnabled ? [`www.${domainName}`] : []), ...additionalDomainNames]
            : undefined;

        this.distribution = new cloudfront.Distribution(this, 'Distribution', {
            defaultRootObject: 'index.html',
            defaultBehavior: {
                origin: origins.S3BucketOrigin.withOriginAccessControl(this.assetsBucket),
                viewerProtocolPolicy: cloudfront.ViewerProtocolPolicy.REDIRECT_TO_HTTPS,
                allowedMethods: cloudfront.AllowedMethods.ALLOW_GET_HEAD_OPTIONS,
                cachePolicy: cloudfront.CachePolicy.CACHING_OPTIMIZED,
                responseHeadersPolicy: this.responseHeadersPolicy,
                compress: true,
                functionAssociations,
            },
            additionalBehaviors: resolvedAdditionalBehaviors,
            httpVersion: cloudfront.HttpVersion.HTTP2_AND_3,
            minimumProtocolVersion: cloudfront.SecurityPolicyProtocol.TLS_V1_2_2021,
            priceClass,
            // The bucket blocks public access, so a missing key comes back as
            // 403 rather than 404. Both have to be mapped or unknown URLs would
            // surface as an access-denied page.
            errorResponses: [
                {
                    httpStatus: 403,
                    responseHttpStatus: 404,
                    responsePagePath: notFoundPagePath,
                    ttl: cdk.Duration.minutes(5),
                },
                {
                    httpStatus: 404,
                    responseHttpStatus: 404,
                    responsePagePath: notFoundPagePath,
                    ttl: cdk.Duration.minutes(5),
                },
            ],
            ...(aliasDomains ? {domainNames: aliasDomains, certificate} : {}),
        });

        if (aliasesEnabled) {
            const target = route53.RecordTarget.fromAlias(
                new route53Targets.CloudFrontTarget(this.distribution),
            );

            this.addAliasRecords('Apex', hostedZone!, domainName!, target);

            if (wwwEnabled) {
                this.addAliasRecords('Www', hostedZone!, `www.${domainName}`, target);
            }

            for (const extra of additionalDomainNames) {
                this.addAliasRecords(
                    `Extra${extra.replace(/[^a-zA-Z0-9]/g, '')}`,
                    hostedZone!,
                    extra,
                    target,
                );
            }
        }

        const source = s3deploy.Source.asset(browserDistPath);

        // Three passes over the same asset, each claiming a slice of the output
        // by pattern and giving it a Cache-Control that matches how the build
        // treats it. `prune` is safe per pass because the include/exclude
        // filters apply to the destination scan as well as the source, so the
        // passes do not delete each other's objects.
        new s3deploy.BucketDeployment(this, 'DeployImmutableAssets', {
            sources: [source],
            destinationBucket: this.assetsBucket,
            cacheControl: [s3deploy.CacheControl.fromString(IMMUTABLE_CACHE_CONTROL)],
            exclude: ['*'],
            include: immutablePatterns,
            prune: true,
            memoryLimit: 1024,
        });

        if (longLivedPatterns.length > 0) {
            new s3deploy.BucketDeployment(this, 'DeployLongLivedAssets', {
                sources: [source],
                destinationBucket: this.assetsBucket,
                cacheControl: [s3deploy.CacheControl.fromString(longLivedCacheControl)],
                exclude: ['*'],
                include: longLivedPatterns,
                prune: true,
                memoryLimit: 1024,
            });
        }

        new s3deploy.BucketDeployment(this, 'DeployDocuments', {
            sources: [source],
            destinationBucket: this.assetsBucket,
            cacheControl: [s3deploy.CacheControl.fromString(documentCacheControl)],
            exclude: [...immutablePatterns, ...longLivedPatterns, ...excludeFromUpload],
            prune: true,
            memoryLimit: 1024,
        });

        new cdk.CfnOutput(this, 'DistributionDomainName', {
            value: this.distribution.distributionDomainName,
        });

        this.distributionIdOutput = new cdk.CfnOutput(this, 'DistributionId', {
            value: this.distribution.distributionId,
            description: 'CloudFront distribution ID, consumed by the pipeline post-deploy invalidation step',
        });

        if (domainName) {
            new cdk.CfnOutput(this, 'SiteUrl', {value: `https://${domainName}`});
        }
    }

    private addAliasRecords(
        prefix: string,
        zone: route53.IHostedZone,
        fqdn: string,
        target: route53.RecordTarget,
    ): void {
        const recordName = recordNameWithinZone(zone, fqdn);

        new route53.ARecord(this, `${prefix}Alias`, {zone, recordName, target});
        new route53.AaaaRecord(this, `${prefix}AliasIpv6`, {zone, recordName, target});
    }
}

